user1= User.create(username:"Daniel",location: "West Seattle", race:"White", gender:"M")
user2= User.create(username:"Lucas",location:"Capitol Hill", race:"White", gender:"M")
user3= User.create(username:"Brad",location:"Snohomish", race:"White", gender:"M")
user4= User.create(username:"Jeff",location:"Greenlake", race:"Black",gender:"M ")
user5= User.create(username:"Lucy",location:"Everett ", race:"Asian",gender:"F")
user6= User.create(username:"Rachel",location:"Eastlake", race:"Hispanic",gender:"F")
user6= User.create(username:"Todd",location:"Greenlake", race:"Black", gender:"M")


# t.string :officer_name
# t.string :badge_number  #could be af3413
# t.string :preicient 
# t.string :unit 
# t.string :rank 
officer1 = Officer.create(officer_name: "Richard E. Bell", badge_number: "6692", preicient: "Ci Coordination Squad", unit: "B105B", rank: "Police Officer")
officer2 = Officer.create(officer_name: "Karen M.Belshay", badge_number: "6304", preicient: "Southwest Pct 1St W - F/W Relief", unit: "B251T", rank: "Police Officer")
officer3 = Officer.create(officer_name: "Robert A. Belshay", badge_number: "6460", preicient: "Intell - Gang Intelligence Detail", unit: "B771C", rank: "Police Officer")
officer4 = Officer.create(officer_name: "Jason S. Bender", badge_number: "6724", preicient: "West Pct 2Nd W - Mary", unit: "B112M", rank: "Police Officer")
officer5 = Officer.create(officer_name: "Joseph M. Bender", badge_number: "6812", preicient: "North Pct Ops - Cpt", unit: "B129C", rank: "Police Officer")
officer6 = Officer.create(officer_name: "Matthew Roy Bendickson", badge_number: "6899", preicient: "North Pct 3Rd W - Lincoln", unit: "B123L", rank: "Police Officer")
officer7 = Officer.create(officer_name: "Devon J. Benner", badge_number: "8309", preicient: "North Pct 1St W - Boy (John)", unit: "B121B", rank: "Police Officer Probation")
officer8 = Officer.create(officer_name: "Daniel A. Benz", badge_number: "6069", preicient: "Crime Analysis Unit - Analysts", unit: "C371A", rank: "Police Officer Detective")
officer9 = Officer.create(officer_name: "Carmen Y. Best", badge_number: "5719", preicient: "Deputy Chief - Operations", unit: "B000", rank: "Deputy Chief Of Police")
officer10 = Officer.create(officer_name: "Denise D. Bouldin", badge_number: "B242T", preicient: "East Pct", unit: "2Nd W - E/G Relief", rank: "Dectective")
officer11 = Officer.create(officer_name: " Scott J Bachler,", badge_number: "B051B", preicient: "Community Outreach - Youth Violence - Schools Detail", unit: "B051B", rank: "Police Officer Detective")
officer12 = Officer.create(officer_name: " Scotty O Bach", badge_number: "B753A", preicient: "Major Crimes Task Force", unit: "NA", rank: "Police Officer Detective")
officer13 = Officer.create(officer_name: "Devlin D. Haag", badge_number: "6051", preicient: "North Pct 2Nd W - Nora", unit: "B122N", rank: "Police Officer")
officer14 = Officer.create(officer_name: "Lisa J. Haakenstad", badge_number: "6025", preicient: "Homicide - Csi Squad", unit: "B711D", rank: "Police Officer Detective")
officer15 = Officer.create(officer_name: "Joe W. Hadley", badge_number: "6978", preicient: "South Pct 3Rd W - Ocean", unit: "B233O", rank: "Police Officer")
officer16 = Officer.create(officer_name: "Edward R. Hagerty", badge_number: "6413", preicient: "Gang Squad B", unit: "B712H", rank: "Police Officer")
officer17 = Officer.create(officer_name: "Christopher M. Hairston", badge_number: "6388", preicient: "Canine Squad", unit: "B623C", rank: "Police Officer")
officer18 = Officer.create(officer_name: "Kevin E. Hastings", badge_number: "4888", preicient: "Harbor - Squad A", unit: "B625A", rank: "Police Sergeant")
officer19 = Officer.create(officer_name: "Bydia J. Haley", badge_number: "4769", preicient: "Evidence Warehouse - Squad C", unit: "B762C", rank: "Evidence Warehouser, Chief")
officer20 = Officer.create(officer_name: "Rik H. Hall", badge_number: "6154", preicient: "Intell - Special Investigations And Assignments Squad", unit: "B772", rank: "Police Officer Detective")
officer21 = Officer.create(officer_name: "Sean R. Hamlin", badge_number: "5833", preicient: "Dv Squad C - Elder Abuse & Fraud", unit: "B721C", rank: "Police Officer")
officer22 = Officer.create(officer_name: "Mar, Bruce T", badge_number: "C020X", preicient: "Hr", unit: "Dept Unavail Personnel", rank: "Police Sergeant")
officer23 = Officer.create(officer_name: "John J Magan", badge_number: "B242E", preicient: "East Pct", unit: "unknown", rank: "Police Officer")
officer24 = Officer.create(officer_name: "Malone, Marty A", badge_number: "B637F", preicient: "East Pct", unit: "P6 Squad", rank: "Parking Enfor Officer")
officer25 = Officer.create(officer_name: "A. J. Marks", badge_number: "B123L", preicient: "North Pct ", unit: "3Rd W - Lincoln", rank: "Police Officer")
officer26 = Officer.create(officer_name: "Ann Martin", badge_number: "B232V", preicient: "South Pct 2", unit: "Nd W - Ocean Relief", rank: "Police Sergeant")
officer27 = Officer.create(officer_name: " Quindelia Martin", badge_number: "B233S", preicient: "South Pct", unit: "3Rd W - Sam", rank: "Police Officer")
officer28 = Officer.create(officer_name: "Martinez Rafael", badge_number: "B621C", preicient: "NA", unit: "Swat - Night Squad 1", rank: "Police Officer")
officer29 = Officer.create(officer_name: "Megan B. Mccowan ", badge_number: "B233S", preicient: "South Pct", unit: "3Rd W - Sam", rank: "Police Officer")
officer30 = Officer.create(officer_name: "Amber Noel Mcleod", badge_number: "C125F", preicient: "West Pct", unit: "Ops - Mounted Patrol", rank: "")
officer31 = Officer.create(officer_name: " Nicolas F Meyst", badge_number: "B252T", preicient: "Southwest Pct", unit: "2Nd W - F/W Relief", rank: "Police Officer")

# t.float :rating
# t.string :review_desc
# t.integer :user_id
# t.integer :officer_id

review1  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review2  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review3  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review4  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review5  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review6  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review7  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review8  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review9  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review10  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review11 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review12 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review13 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review14  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review15  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review16 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review17  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review18 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review19  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review20  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review21  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review22  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review23 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review24  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review25  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review26  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review27  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review28  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review29  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review30  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review31  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review32  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review33  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review34  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review35  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review36  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review37  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review38  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review39  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review40  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review41  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review42  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review43  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review44  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review46  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review45  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review47  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review48  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review49  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review50  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review52  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review134  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review1456  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review1234 = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review145  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review165  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review3453211  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review5341  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review1243  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review3411  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review3451  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review45631  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review551  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review6661  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review5441  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review456  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review75641  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review561  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review78971  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review3551  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review2342341  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review23423  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review234231  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review234231  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review1212  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")
review111  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 10, review_desc:  "Exemplary")
review2342  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 8, review_desc:  "Good")
review32421  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 6, review_desc: "Fair")
review2342  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 3, review_desc: "Rough")
review234  = Review.create(user: User.all.sample, officer: Officer.all.sample, rating: 1, review_desc: "Violent")

puts "it seeded"